name: OpenSpace
pygments: true

exclude: ["README.md", "Gemfile", "Gemfile.lock", "Procfile", "config.ru"]

assets:
  compress:
    css: 'sass'
    js: 'uglifier'
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

