name: OpenSpace
url: "http://agiles-mexico.github.io/openspace-site"

exclude: ["README.md", "Gemfile", "Gemfile.lock", "Procfile", "config.ru"]

assets:
  baseurl: /openspace-site/assets/
  compress:
    css: 'sass'
    js: 'uglifier'
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

